# Dependencies
markdown:         kramdown

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Falez
tagline:          ''
description:      'Personal website of Mohamad Faris Zakwan.'
url:              falez.github.io
baseurl:          /

author:
  name:           'Mohamad Faris Zakwan'

paginate:         5

# Custom vars
version:          2.1.0

portfolio: /portfolio
